# Generated by Django 5.1.2 on 2024-10-13 05:38

import contentManagementPortal.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentManagementPortal', '0005_article_uploaded_by_article_uploaded_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='transcript',
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=contentManagementPortal.models.generate_new_filename),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=contentManagementPortal.models.generate_new_filename),
        ),
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.FileField(upload_to=contentManagementPortal.models.generate_new_filename),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contentManagementPortal.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contentManagementPortal.category'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='video_file',
            field=models.FileField(upload_to=contentManagementPortal.models.generate_new_filename),
        ),
    ]
