# Generated by Django 4.2.2 on 2024-10-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentManagementPortal', '0007_accessgroup_permissions_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessgroup',
            name='permissions_description',
            field=models.CharField(max_length=500),
        ),
    ]
