# Generated by Django 4.2.2 on 2024-10-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentManagementPortal', '0008_alter_accessgroup_permissions_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessgroup',
            name='permissions_description',
            field=models.CharField(default='No permissions description available', max_length=500),
        ),
    ]
